import { readFileSync } from "node:fs";

import {
  formats,
  propertyFormatNames,
  transformGroups,
} from "style-dictionary/enums";

import { formattedVariables } from "style-dictionary/utils";

const portableHtmlTemplate = readFileSync(
  new URL("./src/docs/templates/portable-html.template.html", import.meta.url),
  "utf8",
);

const portableThemeMarker = "/* __TAILWIND_THEME__ */";

const isColor = (token) => (token.$type ?? token.type) === "color";

function replaceIndentedMarker(template, marker, content) {
  const markerLine = template
    .split(/\r?\n/)
    .find((line) => line.trim() === marker);

  if (!markerLine) {
    throw new Error(`Portable HTML template is missing ${marker}`);
  }

  const indentation = markerLine.slice(0, markerLine.indexOf(marker));
  const indentedContent = content
    .split("\n")
    .map((line) => (line ? `${indentation}${line}` : line))
    .join("\n");

  return template.replace(markerLine, indentedContent);
}

function formatTailwindTheme({ dictionary, options }) {
  const variables = formattedVariables({
    format: propertyFormatNames.css,

    dictionary,

    outputReferences: options.outputReferences,

    usesDtcg: true,

    sort: "name",

    formatting: {
      indentation: "  ",
    },
  });

  return `@theme static {
  /* --color-*: initial; */

${variables}
}`;
}

export default {
  source: ["src/tokens/source/**/*.json"],

  usesDtcg: true,

  hooks: {
    formats: {
      "tailwind/theme": ({ dictionary, options }) => {
        const theme = formatTailwindTheme({
          dictionary,
          options,
        });

        return `/*
 * GENERATED BY STYLE DICTIONARY.
 * DO NOT EDIT MANUALLY.
 */

${theme}
`;
      },

      "docs/portable-html": ({ dictionary, options }) => {
        const theme = formatTailwindTheme({
          dictionary,
          options,
        });

        return replaceIndentedMarker(
          portableHtmlTemplate,
          portableThemeMarker,
          theme,
        );
      },
    },
  },

  platforms: {
    tailwind: {
      transformGroup: transformGroups.css,

      buildPath: "src/styles/generated/",

      files: [
        {
          destination: "colors.css",

          format: "tailwind/theme",

          filter: isColor,

          options: {
            outputReferences: true,
          },
        },
      ],
    },

    docs: {
      transformGroup: transformGroups.css,

      buildPath: "src/tokens/generated/",

      files: [
        {
          destination: "colors.json",

          format: formats.jsonFlat,

          filter: isColor,
        },
      ],
    },

    portable: {
      transformGroup: transformGroups.css,

      buildPath: "src/docs/generated/",

      files: [
        {
          destination: "portable-html.html",

          format: "docs/portable-html",

          filter: isColor,

          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
